name: Code Cleanup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint 'client/**/*.tsx' --fix

      - name: Run Prettier
        run: npx prettier --write 'client/**/*.tsx'

      - name: Run ts-prune
        run: npx ts-prune
